# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app.kubernetes.io/name: new-api
#     process: web
#   name: new-api-web
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: new-api
#       process: web
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: new-api
#         process: web
#     spec:
#       containers:
#       - env:
#         - name: PORT
#           value: "3000"
#         envFrom:
#         - configMapRef:
#             name: new-api
#         image: docker.io/odenigbojohnmary/bravado:final
#         imagePullPolicy: Always
#         name: new-api-web
#         ports:
#         - containerPort: 3000
#           name: http
#           protocol: TCP
#         readinessProbe:
#           httpGet:
#             path: /health_check
#             port: 3000
#           initialDelaySeconds: 10
#           periodSeconds: 10
#           timeoutSeconds: 2
#         # livenessProbe:
#         #   httpGet:
#         #     path: /
#         #     port: 3000
#         #   initialDelaySeconds: 70
#         #   periodSeconds: 10
#         #   timeoutSeconds: 2
#         resources:
#           limits:
#             cpu: "700m"
#             memory: "1000Mi"
#           requests:
#             cpu: "500m"
#             memory: "700Mi"
#       restartPolicy: Always
