apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-v1.fullname" . }}
  labels:
    {{- include "base-v1.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "base-v1.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      annotations:
        checksum/config: {{ print $.Template.BasePath "/configmap.yaml" . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "base-v1.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapRef.name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http_port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 120 # how long to wait before checking
            periodSeconds: 20 # how long to wait between checks
            successThreshold: 2 # how many successes to hit before accepting
            failureThreshold: 3 # how many failures to accept before failing
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
