apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-v1.fullname" . }}
  labels:
    {{- include "base-v1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: 'base-v1-http-port'
      port: {{ .Values.service.http_port }}
      targetPort: {{ .Values.service.http_port }}
      protocol: TCP
    - name: 'base-v1-grpc-port'
      port: {{ .Values.service.grpc_port }}
      targetPort: {{ .Values.service.grpc_port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "base-v1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}