groups:
- name: devops demo alert
  rules:
  - alert: High Pod Memory
    expr: sum(container_memory_usage_bytes) > 1
    for: 2m
    labels:
      severity: slack
    annotations:
      summary: High Memory Usage