# Default values for micro-inventory-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    # number of pods to be added per time.
    maxSurge: 1
    # number of pods to be unavailable during a rolling update.
    maxUnavailable: 0
    
image:
  repository: docker.io/odenigbojohnmary/bravado
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: final

imagePullSecrets: []
nameOverride: "new-api-web"
fullnameOverride: "new-api-web"

valueFrom:
    secretKeyRef:
        name: micro-inventory-service-secrets

service:
    type: NodePort
    http_port: 3000

configMapRef:
  name: new-api

ingress:
    enabled: false
    annotations:
        {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
    hosts:
        - host: #TODO add host
          paths:
              - backend:
                serviceName: new-api-web
                servicePort: 4020

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 1000m
    #   memory: 512Mi
    # requests:
    #   cpu: 300m
    #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
